-- 2026.03.06 고객지원팀 A/S 부품·인건비 단가표 (작성: 남현우 팀장)
-- 원본: WMS / SPD / OHD PDF + 통합 엑셀. 변경후(적용) 단가.

ALTER TABLE public.support_as_unit_prices
  ADD COLUMN IF NOT EXISTS product_line text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS name_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS unit text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'part',
  ADD COLUMN IF NOT EXISTS source_key text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'support_as_unit_prices_kind_check'
  ) THEN
    ALTER TABLE public.support_as_unit_prices
      ADD CONSTRAINT support_as_unit_prices_kind_check
      CHECK (kind IN ('part', 'labor'));
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS support_as_unit_prices_source_key_uidx
  ON public.support_as_unit_prices (source_key);

CREATE INDEX IF NOT EXISTS support_as_unit_prices_line_idx
  ON public.support_as_unit_prices (deleted_at, kind, product_line, sort_order);

COMMENT ON COLUMN public.support_as_unit_prices.product_line IS 'WMS / SPD / OHD-수납형 / OHD-산업용 / OHD-주택차고문 / OHD';
COMMENT ON COLUMN public.support_as_unit_prices.kind IS 'part=부품, labor=인건비';
COMMENT ON COLUMN public.support_as_unit_prices.source_key IS '공식 단가표 시드 키. 재배포 시 upsert.';

INSERT INTO public.support_as_unit_prices (
  source_key, kind, product_line, category, name, name_en, spec, unit, price, note, sort_order,
  created_by, created_by_name, updated_by, updated_by_name
)
SELECT
  v.source_key, v.kind, v.product_line, v.category, v.name, v.name_en, v.spec, v.unit, v.price, v.note, v.sort_order,
  'catalog-20260306',
  '남현우 팀장',
  'catalog-20260306',
  '남현우 팀장'
FROM (VALUES
  ('part|WMS|CONTROLLER 전자제어장치|서보 컨트롤러|SERVO CONTROLLER|SET', 'part', 'WMS', 'CONTROLLER 전자제어장치', '서보 컨트롤러', 'SERVO CONTROLLER', '', 'SET', 300000, '', 1),
  ('part|WMS|MOTOR 모터|서보 모터|SERVO MOTOR|SET', 'part', 'WMS', 'MOTOR 모터', '서보 모터', 'SERVO MOTOR', '', 'SET', 700000, '', 2),
  ('part|WMS|PANEL PART 판넬 파트|WMS판넬|WMS PANEL|장', 'part', 'WMS', 'PANEL PART 판넬 파트', 'WMS판넬', 'WMS PANEL', '', '장', 300000, '', 3),
  ('part|WMS|PANEL PART 판넬 파트|롤러|STEEL ROLLER|EA', 'part', 'WMS', 'PANEL PART 판넬 파트', '롤러', 'STEEL ROLLER', '', 'EA', 30000, '', 4),
  ('part|WMS|PANEL PART 판넬 파트|상/하부 캡 / 씰|TOP/BOTTOM CAP / SEAL|EA', 'part', 'WMS', 'PANEL PART 판넬 파트', '상/하부 캡 / 씰', 'TOP/BOTTOM CAP / SEAL', '', 'EA', 150000, '', 5),
  ('part|WMS|FRAME PART 프레임 파트|트랙|TRACK|m', 'part', 'WMS', 'FRAME PART 프레임 파트', '트랙', 'TRACK', '', 'm', 80000, '', 6),
  ('part|WMS|FRAME PART 프레임 파트|와이어 드럼|WIRE DRUM|SET', 'part', 'WMS', 'FRAME PART 프레임 파트', '와이어 드럼', 'WIRE DRUM', '', 'SET', 200000, '', 7),
  ('part|WMS|FRAME PART 프레임 파트|토션 스프링|TORSION SPRING|EA', 'part', 'WMS', 'FRAME PART 프레임 파트', '토션 스프링', 'TORSION SPRING', '', 'EA', 200000, '', 8),
  ('part|WMS|FRAME PART 프레임 파트|샤프트|SHAFT|EA', 'part', 'WMS', 'FRAME PART 프레임 파트', '샤프트', 'SHAFT', '', 'EA', 100000, '', 9),
  ('part|WMS|FRAME PART 프레임 파트|끼임방지 씰|SIDE SEAL|m', 'part', 'WMS', 'FRAME PART 프레임 파트', '끼임방지 씰', 'SIDE SEAL', '', 'm', 20000, '', 10),
  ('part|WMS|HINGE PART 힌지 파트|사이드힌지|SIDE HINGE|EA', 'part', 'WMS', 'HINGE PART 힌지 파트', '사이드힌지', 'SIDE HINGE', '', 'EA', 30000, '', 11),
  ('part|WMS|HINGE PART 힌지 파트|0번힌지|CONTROL HINGE|EA', 'part', 'WMS', 'HINGE PART 힌지 파트', '0번힌지', 'CONTROL HINGE', '', 'EA', 15000, '', 12),
  ('part|WMS|HINGE PART 힌지 파트|하부힌지|BOTTOM HINGE|EA', 'part', 'WMS', 'HINGE PART 힌지 파트', '하부힌지', 'BOTTOM HINGE', '', 'EA', 60000, '', 13),
  ('part|WMS|HINGE PART 힌지 파트|탑힌지|TOP HINGE|EA', 'part', 'WMS', 'HINGE PART 힌지 파트', '탑힌지', 'TOP HINGE', '', 'EA', 30000, '', 14),
  ('part|WMS|COVER PART 커버 파트|조인트 커버|JOINT COVER|M', 'part', 'WMS', 'COVER PART 커버 파트', '조인트 커버', 'JOINT COVER', '', 'M', 30000, '', 15),
  ('part|WMS|COVER PART 커버 파트|드럼 커버|DRUM COVER(SUS)|SET', 'part', 'WMS', 'COVER PART 커버 파트', '드럼 커버', 'DRUM COVER(SUS)', '', 'SET', 300000, '', 16),
  ('part|WMS|ETC 기타|추락방지장치|FALL PREVENTION SYSTEM|EA', 'part', 'WMS', 'ETC 기타', '추락방지장치', 'FALL PREVENTION SYSTEM', '', 'EA', 150000, '', 17),
  ('part|WMS|ETC 기타|압력센서|PRESSURE SENSOR|EA', 'part', 'WMS', 'ETC 기타', '압력센서', 'PRESSURE SENSOR', '', 'EA', 150000, '', 18),
  ('part|WMS|ETC 기타|포토 센서|PHOTO SENSOR|EA', 'part', 'WMS', 'ETC 기타', '포토 센서', 'PHOTO SENSOR', '', 'EA', 150000, '', 19),
  ('part|WMS|ETC 기타|풀감지 센서|CURTAIN SENSOR|EA', 'part', 'WMS', 'ETC 기타', '풀감지 센서', 'CURTAIN SENSOR', '', 'EA', 550000, '', 20),
  ('part|WMS|ETC 기타|경광등|WARNING LAMP|EA', 'part', 'WMS', 'ETC 기타', '경광등', 'WARNING LAMP', '', 'EA', 150000, '', 21),
  ('part|WMS|ETC 기타|3점 스위치|3POINT SWITCH|EA', 'part', 'WMS', 'ETC 기타', '3점 스위치', '3POINT SWITCH', '', 'EA', 70000, '', 22),
  ('part|WMS|ETC 기타|와이어|WIRE|SET', 'part', 'WMS', 'ETC 기타', '와이어', 'WIRE', '', 'SET', 100000, '', 23),
  ('part|SPD|C-1/C-2 기본형/슬림형|드럼 커버|DRUM COVER|', 'part', 'SPD', 'C-1/C-2 기본형/슬림형', '드럼 커버', 'DRUM COVER', '', '', 120000, '호환불가', 24),
  ('part|SPD|C-1/C-2 기본형/슬림형|드럼 하부 커버|DRUM JOINT COVER|', 'part', 'SPD', 'C-1/C-2 기본형/슬림형', '드럼 하부 커버', 'DRUM JOINT COVER', '', '', 50000, '호환불가', 25),
  ('part|SPD|C-1/C-2 기본형/슬림형|가이드 레일|GUIDE RAIL(ㄱ)|', 'part', 'SPD', 'C-1/C-2 기본형/슬림형', '가이드 레일', 'GUIDE RAIL(ㄱ)', '', '', 90000, '호환불가', 26),
  ('part|SPD|C-1/C-2 기본형/슬림형|프레임 커버|FRAME COVER|m', 'part', 'SPD', 'C-1/C-2 기본형/슬림형', '프레임 커버', 'FRAME COVER', '', 'm', 80000, '호환불가', 27),
  ('part|SPD|C-1/C-2 기본형/슬림형|브러쉬 레일|BRUSH RAIL(ㄷ)|', 'part', 'SPD', 'C-1/C-2 기본형/슬림형', '브러쉬 레일', 'BRUSH RAIL(ㄷ)', '', '', 120000, '호환불가', 28),
  ('part|SPD|C-1/C-2 기본형/슬림형|윈드바|WIND BAR|', 'part', 'SPD', 'C-1/C-2 기본형/슬림형', '윈드바', 'WIND BAR', '', '', 50000, '타사 80,000원', 29),
  ('part|SPD|C-1/C-2 기본형/슬림형|하단바|BOTTOM BAR|', 'part', 'SPD', 'C-1/C-2 기본형/슬림형', '하단바', 'BOTTOM BAR', '', '', 120000, '타사 150,000원', 30),
  ('part|SPD|C-3 복구형|드럼 커버|DRUM COVER|', 'part', 'SPD', 'C-3 복구형', '드럼 커버', 'DRUM COVER', '', '', 150000, '호환불가', 31),
  ('part|SPD|C-3 복구형|드럼 상부 커버|DRUM TOP COVER|', 'part', 'SPD', 'C-3 복구형', '드럼 상부 커버', 'DRUM TOP COVER', '', '', 50000, '호환불가', 32),
  ('part|SPD|C-3 복구형|드럼 하부 커버|DRUM JOINT COVER|', 'part', 'SPD', 'C-3 복구형', '드럼 하부 커버', 'DRUM JOINT COVER', '', '', 100000, '호환불가', 33),
  ('part|SPD|C-3 복구형|PVC 가이드 레일|PVC GUIDE RAIL|m', 'part', 'SPD', 'C-3 복구형', 'PVC 가이드 레일', 'PVC GUIDE RAIL', '', 'm', 130000, '호환불가', 34),
  ('part|SPD|C-3 복구형|프레임 커버|FRAME COVER|', 'part', 'SPD', 'C-3 복구형', '프레임 커버', 'FRAME COVER', '', '', 80000, '호환불가', 35),
  ('part|SPD|C-3 복구형|프레임 백커버|FRAME BACK COVER(ㄱ)|', 'part', 'SPD', 'C-3 복구형', '프레임 백커버', 'FRAME BACK COVER(ㄱ)', '', '', 75000, '호환불가', 36),
  ('part|SPD|SHEET 시트|블랙 시트(하단바)|1T SHEET (BOTTOM BAR)|M', 'part', 'SPD', 'SHEET 시트', '블랙 시트(하단바)', '1T SHEET (BOTTOM BAR)', '', 'M', 80000, '타사 120,000원', 37),
  ('part|SPD|SHEET 시트|오렌지/그레이/블루 시트|2T SHEET|m', 'part', 'SPD', 'SHEET 시트', '오렌지/그레이/블루 시트', '2T SHEET', '', 'm', 120000, '타사 180,000원', 38),
  ('part|SPD|SHEET 시트|투명창|CLEAR SHEET|m²', 'part', 'SPD', 'SHEET 시트', '투명창', 'CLEAR SHEET', '', 'm²', 120000, '타사 180,000원', 39),
  ('part|SPD|SHEET 시트|인쇄 단면|PRINTING (단)|면', 'part', 'SPD', 'SHEET 시트', '인쇄 단면', 'PRINTING (단)', '', '면', 300000, '타사 300,000원', 40),
  ('part|SPD|SHEET 시트|인쇄 양면|PRINTING (양)|면', 'part', 'SPD', 'SHEET 시트', '인쇄 양면', 'PRINTING (양)', '', '면', 400000, '타사 400,000원', 41),
  ('part|SPD|MOTOR 모터|반마력|HYPONIC 0.4KW (0.5HP)|SET', 'part', 'SPD', 'MOTOR 모터', '반마력', 'HYPONIC 0.4KW (0.5HP)', '', 'SET', 800000, '타사 1,200,000원', 42),
  ('part|SPD|MOTOR 모터|1마력|HYPONIC 0.75KW (1HP)|SET', 'part', 'SPD', 'MOTOR 모터', '1마력', 'HYPONIC 0.75KW (1HP)', '', 'SET', 900000, '타사 1,200,000원', 43),
  ('part|SPD|MOTOR 모터|2마력|HYPONIC 1.5KW (2HP)|SET', 'part', 'SPD', 'MOTOR 모터', '2마력', 'HYPONIC 1.5KW (2HP)', '', 'SET', 1300000, '타사 1,600,000원', 44),
  ('part|SPD|MOTOR 모터|반마력|ALTAX 0.4KW (0.5HP)|SET', 'part', 'SPD', 'MOTOR 모터', '반마력', 'ALTAX 0.4KW (0.5HP)', '', 'SET', 900000, '타사 1,200,000원', 45),
  ('part|SPD|MOTOR 모터|1마력|ALTAX 0.75KW (1HP)|SET', 'part', 'SPD', 'MOTOR 모터', '1마력', 'ALTAX 0.75KW (1HP)', '', 'SET', 900000, '타사 1,200,000원', 46),
  ('part|SPD|MOTOR 모터|서보 모터 0.4KW|SERVO MOTOR 0.4KW|SET', 'part', 'SPD', 'MOTOR 모터', '서보 모터 0.4KW', 'SERVO MOTOR 0.4KW', '', 'SET', 600000, '신규 · 타사 1,000,000원', 47),
  ('part|SPD|MOTOR 모터|서보 모터 0.75KW|SERVO MOTOR 0.75KW|SET', 'part', 'SPD', 'MOTOR 모터', '서보 모터 0.75KW', 'SERVO MOTOR 0.75KW', '', 'SET', 700000, '신규 · 타사 1,100,000원', 48),
  ('part|SPD|MOTOR 모터|서보 모터 1.5KW|SERVO MOTOR 1.5KW|SET', 'part', 'SPD', 'MOTOR 모터', '서보 모터 1.5KW', 'SERVO MOTOR 1.5KW', '', 'SET', 900000, '신규 · 타사 1,300,000원', 49),
  ('part|SPD|CONTROLLER 전자제어장치|메인보드|CONTROLLER (MAIN)|SET', 'part', 'SPD', 'CONTROLLER 전자제어장치', '메인보드', 'CONTROLLER (MAIN)', '', 'SET', 900000, '타사 1,600,000원', 50),
  ('part|SPD|CONTROLLER 전자제어장치|디스플레이보드|CONTROLLER (DISPLAY)|SET', 'part', 'SPD', 'CONTROLLER 전자제어장치', '디스플레이보드', 'CONTROLLER (DISPLAY)', '', 'SET', 200000, '', 51),
  ('part|SPD|CONTROLLER 전자제어장치|신규 컨트롤러 A1|NEW CONTROLLER A1|SET', 'part', 'SPD', 'CONTROLLER 전자제어장치', '신규 컨트롤러 A1', 'NEW CONTROLLER A1', '', 'SET', 400000, '신규 · 타사 600,000원', 52),
  ('part|SPD|CONTROLLER 전자제어장치|신규 컨트롤러 A2|NEW CONTROLLER A2|SET', 'part', 'SPD', 'CONTROLLER 전자제어장치', '신규 컨트롤러 A2', 'NEW CONTROLLER A2', '', 'SET', 500000, '신규 · 타사 700,000원', 53),
  ('part|SPD|CONTROLLER 전자제어장치|컨트롤러 하이박스|CONTROLLER HIGHBOX|SET', 'part', 'SPD', 'CONTROLLER 전자제어장치', '컨트롤러 하이박스', 'CONTROLLER HIGHBOX', '', 'SET', 100000, '신규 · 타사 100,000원', 54),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|엔코더|ENCODER|SET', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '엔코더', 'ENCODER', '', 'SET', 150000, '타사 200,000원', 55),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|포토 센서|PHOTO SENSOR|SET', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '포토 센서', 'PHOTO SENSOR', '', 'SET', 150000, '타사 200,000원', 56),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|루프 센서|LOOP SENSOR|SET', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '루프 센서', 'LOOP SENSOR', '', 'SET', 200000, '타사 250,000원', 57),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|어플리스 센서|MICROWAVE MOTION SENSOR|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '어플리스 센서', 'MICROWAVE MOTION SENSOR', '', 'EA', 400000, '타사 500,000원', 58),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|헬로 센서|HELLO SENSOR|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '헬로 센서', 'HELLO SENSOR', '', 'EA', 150000, '신규 · 타사 250,000원', 59),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|헬리오스 센서|HELIOS SENSOR|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '헬리오스 센서', 'HELIOS SENSOR', '', 'EA', 500000, '신규 · 타사 700,000원', 60),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|적외선 센서|INFRARED SENSOR|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '적외선 센서', 'INFRARED SENSOR', '', 'EA', 200000, '타사 300,000원', 61),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|압력 센서|PRESSURE SENSOR|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '압력 센서', 'PRESSURE SENSOR', '', 'EA', 200000, '타사 300,000원', 62),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|풀감지센서|CURTAIN SENSOR|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '풀감지센서', 'CURTAIN SENSOR', '', 'EA', 500000, '타사 700,000원', 63),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|경광등|WARNING LAMP|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '경광등', 'WARNING LAMP', '', 'EA', 150000, '타사 200,000원', 64),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|1점 스위치|1 POINT SWITCH|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '1점 스위치', '1 POINT SWITCH', '', 'EA', 300000, '타사 50,000원', 65),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|스위치 하이박스|SWITCH HIGHBOX|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '스위치 하이박스', 'SWITCH HIGHBOX', '', 'EA', 200000, '타사 30,000원', 66),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|풀 스위치|PULL SWITCH|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '풀 스위치', 'PULL SWITCH', '', 'EA', 100000, '타사 200,000원', 67),
  ('part|SPD|SENSOR/SWITCH 센서/스위치|근접 스위치|PROXIMITY SWITCH|EA', 'part', 'SPD', 'SENSOR/SWITCH 센서/스위치', '근접 스위치', 'PROXIMITY SWITCH', '', 'EA', 150000, '타사 200,000원', 68),
  ('part|SPD|REMOTE CONTROL 리모컨|다채널 수신기(달인)|MULTI CHANNEL RECEPTION (DALIN)|EA', 'part', 'SPD', 'REMOTE CONTROL 리모컨', '다채널 수신기(달인)', 'MULTI CHANNEL RECEPTION (DALIN)', '', 'EA', 200000, '타사 300,000원', 69),
  ('part|SPD|REMOTE CONTROL 리모컨|다채널 송신기(달인)|MULTI CHANNEL REMOCON (DALIN)|EA', 'part', 'SPD', 'REMOTE CONTROL 리모컨', '다채널 송신기(달인)', 'MULTI CHANNEL REMOCON (DALIN)', '', 'EA', 150000, '타사 200,000원', 70),
  ('part|SPD|REMOTE CONTROL 리모컨|다채널 수신기|MULTI CHANNEL RECEIVER|EA', 'part', 'SPD', 'REMOTE CONTROL 리모컨', '다채널 수신기', 'MULTI CHANNEL RECEIVER', '', 'EA', 150000, '타사 200,000원', 71),
  ('part|SPD|REMOTE CONTROL 리모컨|다채널 송신기|MULTI CHANNEL TRANSMITTER|EA', 'part', 'SPD', 'REMOTE CONTROL 리모컨', '다채널 송신기', 'MULTI CHANNEL TRANSMITTER', '', 'EA', 70000, '타사 100,000원', 72),
  ('part|SPD|REMOTE CONTROL 리모컨|지게차 리모컨|FORKLIFT REMOCON|EA', 'part', 'SPD', 'REMOTE CONTROL 리모컨', '지게차 리모컨', 'FORKLIFT REMOCON', '', 'EA', 100000, '타사 150,000원', 73),
  ('part|SPD|REMOTE CONTROL 리모컨|리츠엔 수신기|RITS-N RECEPTION|EA', 'part', 'SPD', 'REMOTE CONTROL 리모컨', '리츠엔 수신기', 'RITS-N RECEPTION', '', 'EA', 150000, '타사 200,000원', 74),
  ('part|SPD|REMOTE CONTROL 리모컨|리츠엔 송신기|RITS-N REMOCON|EA', 'part', 'SPD', 'REMOTE CONTROL 리모컨', '리츠엔 송신기', 'RITS-N REMOCON', '', 'EA', 50000, '타사 70,000원', 75),
  ('part|SPD|C-1 DRUM PART 기본형 드럼파트|사이드 브라켓|SIDE BRACKET|EA', 'part', 'SPD', 'C-1 DRUM PART 기본형 드럼파트', '사이드 브라켓', 'SIDE BRACKET', '', 'EA', 70000, '2EA · 호환불가', 76),
  ('part|SPD|C-1 DRUM PART 기본형 드럼파트|베어링|BEARING|EA', 'part', 'SPD', 'C-1 DRUM PART 기본형 드럼파트', '베어링', 'BEARING', '', 'EA', 30000, '2EA · 호환불가', 77),
  ('part|SPD|C-1 DRUM PART 기본형 드럼파트|샤프트|SHAFT|EA', 'part', 'SPD', 'C-1 DRUM PART 기본형 드럼파트', '샤프트', 'SHAFT', '', 'EA', 70000, '2EA · 호환불가', 78),
  ('part|SPD|C-1 DRUM PART 기본형 드럼파트|롤파이프|ROLL PIPE|m', 'part', 'SPD', 'C-1 DRUM PART 기본형 드럼파트', '롤파이프', 'ROLL PIPE', '', 'm', 60000, '호환불가', 79),
  ('part|SPD|C-1 DRUM PART 기본형 드럼파트|백판|BACK HOUSING|m', 'part', 'SPD', 'C-1 DRUM PART 기본형 드럼파트', '백판', 'BACK HOUSING', '', 'm', 60000, '호환불가', 80),
  ('part|SPD|C-1 DRUM PART 기본형 드럼파트|모터 커버|MOTOR COVER(SUS)|EA', 'part', 'SPD', 'C-1 DRUM PART 기본형 드럼파트', '모터 커버', 'MOTOR COVER(SUS)', '', 'EA', 150000, '호환불가', 81),
  ('part|SPD|C-2 DRUM PART 슬림형 드럼파트|사이드 브라켓|SIDE BRACKET|EA', 'part', 'SPD', 'C-2 DRUM PART 슬림형 드럼파트', '사이드 브라켓', 'SIDE BRACKET', '', 'EA', 70000, '2EA · 호환불가', 82),
  ('part|SPD|C-2 DRUM PART 슬림형 드럼파트|베어링|BEARING|EA', 'part', 'SPD', 'C-2 DRUM PART 슬림형 드럼파트', '베어링', 'BEARING', '', 'EA', 30000, '2EA · 호환불가', 83),
  ('part|SPD|C-2 DRUM PART 슬림형 드럼파트|샤프트|SHAFT|EA', 'part', 'SPD', 'C-2 DRUM PART 슬림형 드럼파트', '샤프트', 'SHAFT', '', 'EA', 80000, '2EA · 호환불가', 84),
  ('part|SPD|C-2 DRUM PART 슬림형 드럼파트|PVC 롤파이프|PVC ROLL PIPE|m', 'part', 'SPD', 'C-2 DRUM PART 슬림형 드럼파트', 'PVC 롤파이프', 'PVC ROLL PIPE', '', 'm', 100000, '호환불가', 85),
  ('part|SPD|C-2 DRUM PART 슬림형 드럼파트|백판|BACK HOUSING|m', 'part', 'SPD', 'C-2 DRUM PART 슬림형 드럼파트', '백판', 'BACK HOUSING', '', 'm', 60000, '호환불가', 86),
  ('part|SPD|C-2 DRUM PART 슬림형 드럼파트|모터 하우징|MOTOR HOUSING|EA', 'part', 'SPD', 'C-2 DRUM PART 슬림형 드럼파트', '모터 하우징', 'MOTOR HOUSING', '', 'EA', 150000, '호환불가', 87),
  ('part|SPD|C-3 DRUM PART 복구형 드럼파트|사이드 브라켓|SIDE BRACKET|EA', 'part', 'SPD', 'C-3 DRUM PART 복구형 드럼파트', '사이드 브라켓', 'SIDE BRACKET', '', 'EA', 90000, '2EA · 호환불가', 88),
  ('part|SPD|C-3 DRUM PART 복구형 드럼파트|베어링|BEARING|EA', 'part', 'SPD', 'C-3 DRUM PART 복구형 드럼파트', '베어링', 'BEARING', '', 'EA', 30000, '4EA · 호환불가', 89),
  ('part|SPD|C-3 DRUM PART 복구형 드럼파트|샤프트|SHAFT|EA', 'part', 'SPD', 'C-3 DRUM PART 복구형 드럼파트', '샤프트', 'SHAFT', '', 'EA', 100000, '4EA · 호환불가', 90),
  ('part|SPD|C-3 DRUM PART 복구형 드럼파트|롤파이프|ROLL PIPE|m', 'part', 'SPD', 'C-3 DRUM PART 복구형 드럼파트', '롤파이프', 'ROLL PIPE', '', 'm', 60000, '2EA · 호환불가', 91),
  ('part|SPD|C-3 DRUM PART 복구형 드럼파트|기어|GEAR|SET', 'part', 'SPD', 'C-3 DRUM PART 복구형 드럼파트', '기어', 'GEAR', '', 'SET', 100000, '호환불가', 92),
  ('part|OHD-수납형|CONTROLLER 전자제어장치|컨트롤러|CONTROLLER|SET', 'part', 'OHD-수납형', 'CONTROLLER 전자제어장치', '컨트롤러', 'CONTROLLER', '', 'SET', 800000, 'TE-2200 · 호환불가', 93),
  ('part|OHD-수납형|CONTROLLER 전자제어장치|엔코더|ENCODER|EA', 'part', 'OHD-수납형', 'CONTROLLER 전자제어장치', '엔코더', 'ENCODER', '', 'EA', 200000, '타사 300,000원', 94),
  ('part|OHD-수납형|MOTOR 모터|1마력|HYPONIC 0.75KW (1HP)|SET', 'part', 'OHD-수납형', 'MOTOR 모터', '1마력', 'HYPONIC 0.75KW (1HP)', '', 'SET', 900000, '타사 1,200,000원', 95),
  ('part|OHD-수납형|MOTOR 모터|반마력|HYPONIC 0.4KW (0.5HP)|SET', 'part', 'OHD-수납형', 'MOTOR 모터', '반마력', 'HYPONIC 0.4KW (0.5HP)', '', 'SET', 900000, '타사 1,200,000원', 96),
  ('part|OHD-수납형|FRAME PART 프레임 파트|프레임 커버|FRAME COVER|m', 'part', 'OHD-수납형', 'FRAME PART 프레임 파트', '프레임 커버', 'FRAME COVER', '', 'm', 80000, '호환불가', 97),
  ('part|OHD-수납형|FRAME PART 프레임 파트|가이드 레일(전면)|GUIDE RAIL (FRONT)|m', 'part', 'OHD-수납형', 'FRAME PART 프레임 파트', '가이드 레일(전면)', 'GUIDE RAIL (FRONT)', '', 'm', 80000, '호환불가', 98),
  ('part|OHD-수납형|FRAME PART 프레임 파트|가이드 레일(후면)|GUIDE RAIL (REAR)|m', 'part', 'OHD-수납형', 'FRAME PART 프레임 파트', '가이드 레일(후면)', 'GUIDE RAIL (REAR)', '', 'm', 120000, '호환불가', 99),
  ('part|OHD-수납형|FRAME PART 프레임 파트|고무발/고정대|SEAL|', 'part', 'OHD-수납형', 'FRAME PART 프레임 파트', '고무발/고정대', 'SEAL', '', '', 40000, '타사 50,000원', 100),
  ('part|OHD-수납형|DRUM PART 드럼 파트|드럼|DRUM ASS''Y|SET', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '드럼', 'DRUM ASS''Y', '', 'SET', 900000, '호환불가', 101),
  ('part|OHD-수납형|DRUM PART 드럼 파트|기어|GEAR|EA', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '기어', 'GEAR', '', 'EA', 60000, '호환불가', 102),
  ('part|OHD-수납형|DRUM PART 드럼 파트|베어링|BEARING|EA', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '베어링', 'BEARING', '', 'EA', 30000, '호환불가', 103),
  ('part|OHD-수납형|DRUM PART 드럼 파트|베어링 하우징|BEARING HOUSING|EA', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '베어링 하우징', 'BEARING HOUSING', '', 'EA', 20000, '호환불가', 104),
  ('part|OHD-수납형|DRUM PART 드럼 파트|샤프트|SHAFT|EA', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '샤프트', 'SHAFT', '', 'EA', 70000, '호환불가', 105),
  ('part|OHD-수납형|DRUM PART 드럼 파트|샤프트 서포터|SHAFT SUPPORT|EA', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '샤프트 서포터', 'SHAFT SUPPORT', '', 'EA', 50000, '호환불가', 106),
  ('part|OHD-수납형|DRUM PART 드럼 파트|체인 50번|CHAIN 50#|EA', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '체인 50번', 'CHAIN 50#', '', 'EA', 100000, '호환불가', 107),
  ('part|OHD-수납형|DRUM PART 드럼 파트|체인 60번|CHAIN 60#|EA', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '체인 60번', 'CHAIN 60#', '', 'EA', 100000, '호환불가', 108),
  ('part|OHD-수납형|DRUM PART 드럼 파트|롤파이프|ROLL PIPE|m', 'part', 'OHD-수납형', 'DRUM PART 드럼 파트', '롤파이프', 'ROLL PIPE', '', 'm', 60000, '호환불가', 109),
  ('part|OHD-수납형|PANEL PART 판넬 파트|우레탄 판넬|URETHANE PANEL|m', 'part', 'OHD-수납형', 'PANEL PART 판넬 파트', '우레탄 판넬', 'URETHANE PANEL', '', 'm', 100000, '타사 150,000원', 110),
  ('part|OHD-수납형|PANEL PART 판넬 파트|판넬캡(상/하부)|PANEL CAP (TOP/BOTTOM)|m', 'part', 'OHD-수납형', 'PANEL PART 판넬 파트', '판넬캡(상/하부)', 'PANEL CAP (TOP/BOTTOM)', '', 'm', 60000, '상/하부 포함 · 호환불가', 111),
  ('part|OHD-수납형|PANEL PART 판넬 파트|엔드캡|END CAP|', 'part', 'OHD-수납형', 'PANEL PART 판넬 파트', '엔드캡', 'END CAP', '', '', 50000, '호환불가', 112),
  ('part|OHD-수납형|PANEL PART 판넬 파트|판넬 롤러|PANEL ROLLER|EA', 'part', 'OHD-수납형', 'PANEL PART 판넬 파트', '판넬 롤러', 'PANEL ROLLER', '', 'EA', 60000, '호환불가', 113),
  ('part|OHD-수납형|PANEL PART 판넬 파트|채광창|WINDOW|', 'part', 'OHD-수납형', 'PANEL PART 판넬 파트', '채광창', 'WINDOW', '', '', 200000, '타사 300,000원', 114),
  ('part|OHD-산업용|CONTROLLER 전자제어장치|컨트롤러|CONTROLLER|SET', 'part', 'OHD-산업용', 'CONTROLLER 전자제어장치', '컨트롤러', 'CONTROLLER', '', 'SET', 900000, '타사 1,200,000원', 115),
  ('part|OHD-산업용|CONTROLLER 전자제어장치|서보 컨트롤러|SERVO CONTROLLER|SET', 'part', 'OHD-산업용', 'CONTROLLER 전자제어장치', '서보 컨트롤러', 'SERVO CONTROLLER', '', 'SET', 500000, '신규 · 타사 700,000원', 116),
  ('part|OHD-산업용|MOTOR 모터|서보 모터|SERVO MOTOR|SET', 'part', 'OHD-산업용', 'MOTOR 모터', '서보 모터', 'SERVO MOTOR', '', 'SET', 900000, '신규 · 타사 1,200,000원', 117),
  ('part|OHD-산업용|PANEL PART 판넬 파트|우레탄 판넬|URETHANE PANEL|m', 'part', 'OHD-산업용', 'PANEL PART 판넬 파트', '우레탄 판넬', 'URETHANE PANEL', '', 'm', 100000, '타사 150,000원', 118),
  ('part|OHD-산업용|PANEL PART 판넬 파트|채광창|WINDOW|', 'part', 'OHD-산업용', 'PANEL PART 판넬 파트', '채광창', 'WINDOW', '', '', 100000, '타사 150,000원', 119),
  ('part|OHD-산업용|PANEL PART 판넬 파트|롤러|STEEL ROLLER|', 'part', 'OHD-산업용', 'PANEL PART 판넬 파트', '롤러', 'STEEL ROLLER', '', '', 30000, '타사 50,000원', 120),
  ('part|OHD-산업용|PANEL PART 판넬 파트|상/하부 캡|TOP/BOTTOM CAP|', 'part', 'OHD-산업용', 'PANEL PART 판넬 파트', '상/하부 캡', 'TOP/BOTTOM CAP', '', '', 35000, '타사 70,000원', 121),
  ('part|OHD-산업용|FRAME PART 프레임 파트|트랙|TRACK|m', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '트랙', 'TRACK', '', 'm', 80000, '호환불가', 122),
  ('part|OHD-산업용|DRUM 드럼|드럼 5인치|DRUM 5인치|SET', 'part', 'OHD-산업용', 'DRUM 드럼', '드럼 5인치', 'DRUM 5인치', '', 'SET', 100000, '호환불가', 123),
  ('part|OHD-산업용|DRUM 드럼|드럼 6인치|DRUM 6인치|SET', 'part', 'OHD-산업용', 'DRUM 드럼', '드럼 6인치', 'DRUM 6인치', '', 'SET', 200000, '호환불가', 124),
  ('part|OHD-산업용|DRUM 드럼|드럼 8인치|DRUM 8인치|SET', 'part', 'OHD-산업용', 'DRUM 드럼', '드럼 8인치', 'DRUM 8인치', '', 'SET', 300000, '호환불가', 125),
  ('part|OHD-산업용|FRAME PART 프레임 파트|토션 스프링 소|TORSION SPRING 소|EA', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '토션 스프링 소', 'TORSION SPRING 소', '', 'EA', 200000, '타사 300,000원', 126),
  ('part|OHD-산업용|FRAME PART 프레임 파트|토션 스프링 중|TORSION SPRING 중|EA', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '토션 스프링 중', 'TORSION SPRING 중', '', 'EA', 300000, '타사 450,000원', 127),
  ('part|OHD-산업용|FRAME PART 프레임 파트|토션 스프링 대|TORSION SPRING 대|EA', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '토션 스프링 대', 'TORSION SPRING 대', '', 'EA', 400000, '타사 600,000원', 128),
  ('part|OHD-산업용|FRAME PART 프레임 파트|샤프트|SHAFT|m', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '샤프트', 'SHAFT', '', 'm', 70000, '타사 100,000원', 129),
  ('part|OHD-산업용|FRAME PART 프레임 파트|스톱퍼|PUSHER SPRING|EA', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '스톱퍼', 'PUSHER SPRING', '', 'EA', 60000, '타사 80,000원', 130),
  ('part|OHD-산업용|FRAME PART 프레임 파트|추락방지장치|FALL PREVENTION SYSTEM|EA', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '추락방지장치', 'FALL PREVENTION SYSTEM', '', 'EA', 200000, '타사 300,000원', 131),
  ('part|OHD-산업용|FRAME PART 프레임 파트|와이어|WIRE|SET', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '와이어', 'WIRE', '', 'SET', 100000, '타사 150,000원', 132),
  ('part|OHD-산업용|FRAME PART 프레임 파트|홀트랙|JOINT BRACKET|m', 'part', 'OHD-산업용', 'FRAME PART 프레임 파트', '홀트랙', 'JOINT BRACKET', '', 'm', 60000, '타사 80,000원', 133),
  ('part|OHD-산업용|HINGE PART 힌지 파트|조절힌지|CONTROL HINGE|EA', 'part', 'OHD-산업용', 'HINGE PART 힌지 파트', '조절힌지', 'CONTROL HINGE', '', 'EA', 30000, '타사 50,000원', 134),
  ('part|OHD-산업용|HINGE PART 힌지 파트|센터힌지|CENTER HINGE|EA', 'part', 'OHD-산업용', 'HINGE PART 힌지 파트', '센터힌지', 'CENTER HINGE', '', 'EA', 15000, '타사 30,000원', 135),
  ('part|OHD-산업용|HINGE PART 힌지 파트|하부힌지|BOTTOM HINGE|EA', 'part', 'OHD-산업용', 'HINGE PART 힌지 파트', '하부힌지', 'BOTTOM HINGE', '', 'EA', 60000, '타사 80,000원', 136),
  ('part|OHD-산업용|HINGE PART 힌지 파트|탑힌지|TOP HINGE|EA', 'part', 'OHD-산업용', 'HINGE PART 힌지 파트', '탑힌지', 'TOP HINGE', '', 'EA', 30000, '타사 50,000원', 137),
  ('part|OHD-주택차고문|ALUMINIUM PART 알루미늄 파트|100×100 각관|SQUARE PIPE 100×100|m', 'part', 'OHD-주택차고문', 'ALUMINIUM PART 알루미늄 파트', '100×100 각관', 'SQUARE PIPE 100×100', '', 'm', 120000, '타사 150,000원', 138),
  ('part|OHD-주택차고문|ALUMINIUM PART 알루미늄 파트|100×45 각관|SQUARE PIPE 100×45|m', 'part', 'OHD-주택차고문', 'ALUMINIUM PART 알루미늄 파트', '100×45 각관', 'SQUARE PIPE 100×45', '', 'm', 90000, '타사 120,000원', 139),
  ('part|OHD-주택차고문|PANEL PART 판넬 파트|우레탄 판넬|URETHANE PANEL|m', 'part', 'OHD-주택차고문', 'PANEL PART 판넬 파트', '우레탄 판넬', 'URETHANE PANEL', '', 'm', 100000, '신규 · 타사 150,000원', 140),
  ('part|OHD-주택차고문|PANEL PART 판넬 파트|사틴펄 판넬|SATIN PEARL PANEL|m', 'part', 'OHD-주택차고문', 'PANEL PART 판넬 파트', '사틴펄 판넬', 'SATIN PEARL PANEL', '', 'm', 700000, '엔드캡 포함 · 타사 800,000원', 141),
  ('part|OHD-주택차고문|PANEL PART 판넬 파트|마블 스톤|MARBLE STONE PANEL|m', 'part', 'OHD-주택차고문', 'PANEL PART 판넬 파트', '마블 스톤', 'MARBLE STONE PANEL', '', 'm', 800000, '엔드캡 포함 · 타사 900,000원', 142),
  ('part|OHD-주택차고문|PANEL PART 판넬 파트|엔드캡|END CAP|EA', 'part', 'OHD-주택차고문', 'PANEL PART 판넬 파트', '엔드캡', 'END CAP', '', 'EA', 30000, '타사 50,000원', 143),
  ('part|OHD-주택차고문|PANEL PART 판넬 파트|채광창 단순교체|WINDOW (단순교체)|EA', 'part', 'OHD-주택차고문', 'PANEL PART 판넬 파트', '채광창 단순교체', 'WINDOW (단순교체)', '', 'EA', 50000, '타사 75,000원', 144),
  ('part|OHD-주택차고문|PANEL PART 판넬 파트|채광창 신규타공|WINDOW (신규타공)|EA', 'part', 'OHD-주택차고문', 'PANEL PART 판넬 파트', '채광창 신규타공', 'WINDOW (신규타공)', '', 'EA', 75000, '타사 100,000원', 145),
  ('part|OHD-주택차고문|RETAINER PART 리테이너 파트|탑 리테이너|TOP RETAINER|EA', 'part', 'OHD-주택차고문', 'RETAINER PART 리테이너 파트', '탑 리테이너', 'TOP RETAINER', '', 'EA', 150000, '단위 M→EA 변경 및 금액 조정 · 타사 200,000원', 146),
  ('part|OHD-주택차고문|RETAINER PART 리테이너 파트|하부 리테이너|BOTTOM RETAINER|EA', 'part', 'OHD-주택차고문', 'RETAINER PART 리테이너 파트', '하부 리테이너', 'BOTTOM RETAINER', '', 'EA', 150000, '단위 M→EA 변경 및 금액 조정 · 타사 200,000원', 147),
  ('part|OHD-주택차고문|RETAINER PART 리테이너 파트|하부씰|BOTTOM SEAL|m', 'part', 'OHD-주택차고문', 'RETAINER PART 리테이너 파트', '하부씰', 'BOTTOM SEAL', '', 'm', 15000, '타사 30,000원', 148),
  ('part|OHD-주택차고문|RETAINER PART 리테이너 파트|사이드씰|SIDE SEAL|m', 'part', 'OHD-주택차고문', 'RETAINER PART 리테이너 파트', '사이드씰', 'SIDE SEAL', '', 'm', 15000, '신규 · 타사 30,000원', 149),
  ('part|OHD-주택차고문|HINGE PART 힌지 파트|조절힌지|CONTROL HINGE|EA', 'part', 'OHD-주택차고문', 'HINGE PART 힌지 파트', '조절힌지', 'CONTROL HINGE', '', 'EA', 30000, '타사 50,000원', 150),
  ('part|OHD-주택차고문|HINGE PART 힌지 파트|센터힌지|CENTER HINGE|EA', 'part', 'OHD-주택차고문', 'HINGE PART 힌지 파트', '센터힌지', 'CENTER HINGE', '', 'EA', 20000, '타사 30,000원', 151),
  ('part|OHD-주택차고문|HINGE PART 힌지 파트|하부힌지|BOTTOM HINGE|EA', 'part', 'OHD-주택차고문', 'HINGE PART 힌지 파트', '하부힌지', 'BOTTOM HINGE', '', 'EA', 60000, '타사 80,000원', 152),
  ('part|OHD-주택차고문|HINGE PART 힌지 파트|탑힌지|TOP HINGE|EA', 'part', 'OHD-주택차고문', 'HINGE PART 힌지 파트', '탑힌지', 'TOP HINGE', '', 'EA', 30000, '타사 50,000원', 153),
  ('part|OHD-주택차고문|SPRING PART 스프링 파트|스프링 50kg|SPRING 50kg|EA', 'part', 'OHD-주택차고문', 'SPRING PART 스프링 파트', '스프링 50kg', 'SPRING 50kg', '', 'EA', 150000, '타사 200,000원', 154),
  ('part|OHD-주택차고문|SPRING PART 스프링 파트|스프링 110kg|SPRING 110kg|EA', 'part', 'OHD-주택차고문', 'SPRING PART 스프링 파트', '스프링 110kg', 'SPRING 110kg', '', 'EA', 200000, '타사 300,000원', 155),
  ('part|OHD-주택차고문|SPRING PART 스프링 파트|스프링 110kg 이상|SPRING 110kg+|EA', 'part', 'OHD-주택차고문', 'SPRING PART 스프링 파트', '스프링 110kg 이상', 'SPRING 110kg+', '', 'EA', 300000, '타사 400,000원', 156),
  ('part|OHD-주택차고문|SPRING PART 스프링 파트|스프링연결대|SPRING CONNECT|EA', 'part', 'OHD-주택차고문', 'SPRING PART 스프링 파트', '스프링연결대', 'SPRING CONNECT', '', 'EA', 50000, '타사 80,000원', 157),
  ('part|OHD-주택차고문|SPRING PART 스프링 파트|스프링폴리|SPRING POLY|EA', 'part', 'OHD-주택차고문', 'SPRING PART 스프링 파트', '스프링폴리', 'SPRING POLY', '', 'EA', 20000, '타사 30,000원', 158),
  ('part|OHD-주택차고문|SPRING PART 스프링 파트|아이볼트|EYE BOLT|EA', 'part', 'OHD-주택차고문', 'SPRING PART 스프링 파트', '아이볼트', 'EYE BOLT', '', 'EA', 15000, '타사 20,000원', 159),
  ('part|OHD-주택차고문|ROLLER PART 롤러 파트|롤러 L=115|ROLLER L=115|EA', 'part', 'OHD-주택차고문', 'ROLLER PART 롤러 파트', '롤러 L=115', 'ROLLER L=115', '', 'EA', 20000, '타사 30,000원', 160),
  ('part|OHD-주택차고문|ROLLER PART 롤러 파트|롤러 L=185|ROLLER L=185|EA', 'part', 'OHD-주택차고문', 'ROLLER PART 롤러 파트', '롤러 L=185', 'ROLLER L=185', '', 'EA', 20000, '타사 30,000원', 161),
  ('part|OHD-주택차고문|TRACK PART 트랙 파트|수직트랙|VERTICAL TRACK|m', 'part', 'OHD-주택차고문', 'TRACK PART 트랙 파트', '수직트랙', 'VERTICAL TRACK', '', 'm', 70000, '타사 90,000원', 162),
  ('part|OHD-주택차고문|TRACK PART 트랙 파트|R트랙|ROUND TRACK|EA', 'part', 'OHD-주택차고문', 'TRACK PART 트랙 파트', 'R트랙', 'ROUND TRACK', '', 'EA', 200000, 'SET: 40만원 · 타사 300,000원', 163),
  ('part|OHD-주택차고문|MOTOR PART 모터 파트|모터/컨트롤러|MOTOR/CONTROLLER|EA', 'part', 'OHD-주택차고문', 'MOTOR PART 모터 파트', '모터/컨트롤러', 'MOTOR/CONTROLLER', '', 'EA', 900000, '타사 1,000,000원', 164),
  ('part|OHD-주택차고문|MOTOR PART 모터 파트|모터 레일|MOTOR RAIL|EA', 'part', 'OHD-주택차고문', 'MOTOR PART 모터 파트', '모터 레일', 'MOTOR RAIL', '', 'EA', 150000, '타사 200,000원', 165),
  ('part|OHD-주택차고문|MOTOR PART 모터 파트|모터연장레일|MOTOR EXTENSION RAIL|EA', 'part', 'OHD-주택차고문', 'MOTOR PART 모터 파트', '모터연장레일', 'MOTOR EXTENSION RAIL', '', 'EA', 100000, '타사 100,000원', 166),
  ('part|OHD-주택차고문|BRACKET PART 브라켓 파트|프래그 브라켓|FLAG BRACKET|EA', 'part', 'OHD-주택차고문', 'BRACKET PART 브라켓 파트', '프래그 브라켓', 'FLAG BRACKET', '', 'EA', 60000, '타사 80,000원', 167),
  ('part|OHD-주택차고문|BRACKET PART 브라켓 파트|잼 브라켓 A/B/D|JAM BRACKET A/B/D|EA', 'part', 'OHD-주택차고문', 'BRACKET PART 브라켓 파트', '잼 브라켓 A/B/D', 'JAM BRACKET A/B/D', '', 'EA', 40000, '타사 60,000원', 168),
  ('part|OHD-주택차고문|REMOTE CONTROL 리모컨 파트|스마트폰 원격제어|SMARTPHONE REMOTE|EA', 'part', 'OHD-주택차고문', 'REMOTE CONTROL 리모컨 파트', '스마트폰 원격제어', 'SMARTPHONE REMOTE', '', 'EA', 700000, '호환불가', 169),
  ('part|OHD-주택차고문|REMOTE CONTROL 리모컨 파트|풀감지 센서|CURTAIN SENSOR|EA', 'part', 'OHD-주택차고문', 'REMOTE CONTROL 리모컨 파트', '풀감지 센서', 'CURTAIN SENSOR', '', 'EA', 500000, '타사 600,000원', 170),
  ('part|OHD-주택차고문|REMOTE CONTROL 리모컨 파트|벽부형(구형)|WALL TYPE (구형)|EA', 'part', 'OHD-주택차고문', 'REMOTE CONTROL 리모컨 파트', '벽부형(구형)', 'WALL TYPE (구형)', '', 'EA', 70000, '호환불가', 171),
  ('part|OHD-주택차고문|REMOTE CONTROL 리모컨 파트|벽부형(신형)|WALL TYPE (신형)|EA', 'part', 'OHD-주택차고문', 'REMOTE CONTROL 리모컨 파트', '벽부형(신형)', 'WALL TYPE (신형)', '', 'EA', 70000, '호환불가', 172),
  ('part|OHD-주택차고문|REMOTE CONTROL 리모컨 파트|번호키|KEYPAD|EA', 'part', 'OHD-주택차고문', 'REMOTE CONTROL 리모컨 파트', '번호키', 'KEYPAD', '', 'EA', 250000, '타사 300,000원', 173),
  ('part|OHD-주택차고문|REMOTE CONTROL 리모컨 파트|선바이저|SUN VISOR|EA', 'part', 'OHD-주택차고문', 'REMOTE CONTROL 리모컨 파트', '선바이저', 'SUN VISOR', '', 'EA', 100000, '호환불가', 174),
  ('part|OHD-주택차고문|REMOTE CONTROL 리모컨 파트|일반|STANDARD REMOCON|EA', 'part', 'OHD-주택차고문', 'REMOTE CONTROL 리모컨 파트', '일반', 'STANDARD REMOCON', '', 'EA', 70000, '호환불가', 175),
  ('labor|WMS|판넬 교체|WMS 도어', 'labor', 'WMS', '인건비', '판넬 교체', '', 'WMS 도어', '', 400000, '2인1조 기준 / 장비대 별도', 1001),
  ('labor|WMS|모터 교체|WMS 도어', 'labor', 'WMS', '인건비', '모터 교체', '', 'WMS 도어', '', 500000, '2인1조 기준 / 장비대 별도', 1002),
  ('labor|WMS|와이어 교체|WMS 도어', 'labor', 'WMS', '인건비', '와이어 교체', '', 'WMS 도어', '', 100000, 'set', 1003),
  ('labor|WMS|스프링 교체|WMS 도어', 'labor', 'WMS', '인건비', '스프링 교체', '', 'WMS 도어', '', 500000, '', 1004),
  ('labor|WMS|기본 출장비|WMS 도어', 'labor', 'WMS', '인건비', '기본 출장비', '', 'WMS 도어', '', 300000, '', 1005),
  ('labor|WMS|철거비|', 'labor', 'WMS', '인건비', '철거비', '', '', '', 500000, '', 1006),
  ('labor|WMS|시공비|', 'labor', 'WMS', '인건비', '시공비', '', '', '', 700000, '', 1007),
  ('labor|SPD|기본 출장비|2인1회 기준 (+작업비/자재비 별도)', 'labor', 'SPD', '인건비', '기본 출장비', '', '2인1회 기준 (+작업비/자재비 별도)', '', 150000, '장비대 별도 청구', 1008),
  ('labor|SPD|시트복구|기본형/슬림형', 'labor', 'SPD', '인건비', '시트복구', '', '기본형/슬림형', '', 150000, '출장비+작업비 300,000원', 1009),
  ('labor|SPD|시트복구|복구형', 'labor', 'SPD', '인건비', '시트복구', '', '복구형', '', 250000, '출장비+작업비 400,000원', 1010),
  ('labor|SPD|시트복구|타사자동문', 'labor', 'SPD', '인건비', '시트복구', '', '타사자동문', '', 550000, '출장비+작업비 700,000원', 1011),
  ('labor|SPD|모터교체|기본형/복구형', 'labor', 'SPD', '인건비', '모터교체', '', '기본형/복구형', '', 150000, '출장비+작업비 300,000원', 1012),
  ('labor|SPD|모터교체|슬림형', 'labor', 'SPD', '인건비', '모터교체', '', '슬림형', '', 450000, '출장비+작업비 600,000원', 1013),
  ('labor|SPD|모터교체|타사자동문', 'labor', 'SPD', '인건비', '모터교체', '', '타사자동문', '', 550000, '출장비+작업비 700,000원', 1014),
  ('labor|SPD|시트교체|기본형/슬림형/복구형', 'labor', 'SPD', '인건비', '시트교체', '', '기본형/슬림형/복구형', '', 350000, '출장비+작업비 500,000원', 1015),
  ('labor|SPD|시트교체|타사자동문', 'labor', 'SPD', '인건비', '시트교체', '', '타사자동문', '', 550000, '출장비+작업비 700,000원', 1016),
  ('labor|SPD|자동문 철거|기본형/슬림형/복구형', 'labor', 'SPD', '인건비', '자동문 철거', '', '기본형/슬림형/복구형', '', 350000, '출장비+작업비 500,000원', 1017),
  ('labor|SPD|자동문 철거|타사자동문', 'labor', 'SPD', '인건비', '자동문 철거', '', '타사자동문', '', 550000, '출장비+작업비 700,000원', 1018),
  ('labor|SPD|자동문 시공|기본형/슬림형/복구형', 'labor', 'SPD', '인건비', '자동문 시공', '', '기본형/슬림형/복구형', '', 550000, '출장비+작업비 700,000원', 1019),
  ('labor|SPD|자동문 이전설치|오프닝 3000×3000 이하', 'labor', 'SPD', '인건비', '자동문 이전설치', '', '오프닝 3000×3000 이하', '', 1050000, '출장비+작업비 1,200,000원', 1020),
  ('labor|SPD|자동문 이전설치|오프닝 4000×4000 이하', 'labor', 'SPD', '인건비', '자동문 이전설치', '', '오프닝 4000×4000 이하', '', 1250000, '출장비+작업비 1,400,000원', 1021),
  ('labor|SPD|자동문 이전설치|오프닝 4000×4000 초과', 'labor', 'SPD', '인건비', '자동문 이전설치', '', '오프닝 4000×4000 초과', '', 1450000, '출장비+작업비 1,600,000원', 1022),
  ('labor|SPD|루프매립|당사', 'labor', 'SPD', '인건비', '루프매립', '', '당사', '', 450000, '출장비+작업비 600,000원', 1023),
  ('labor|SPD|루프매립|타사자동문', 'labor', 'SPD', '인건비', '루프매립', '', '타사자동문', '', 550000, '출장비+작업비 700,000원', 1024),
  ('labor|SPD|스위치 교체|당사', 'labor', 'SPD', '인건비', '스위치 교체', '', '당사', '', 150000, '출장비+작업비 300,000원', 1025),
  ('labor|SPD|스위치 교체|타사자동문', 'labor', 'SPD', '인건비', '스위치 교체', '', '타사자동문', '', 250000, '출장비+작업비 400,000원', 1026),
  ('labor|SPD|안전센서 교체|당사', 'labor', 'SPD', '인건비', '안전센서 교체', '', '당사', '', 150000, '출장비+작업비 300,000원', 1027),
  ('labor|SPD|안전센서 교체|타사자동문', 'labor', 'SPD', '인건비', '안전센서 교체', '', '타사자동문', '', 250000, '출장비+작업비 400,000원', 1028),
  ('labor|SPD|프레임 교체|', 'labor', 'SPD', '인건비', '프레임 교체', '', '', '', 150000, '출장비+작업비 300,000원', 1029),
  ('labor|SPD|가이드레일 교체|기본형/슬림형', 'labor', 'SPD', '인건비', '가이드레일 교체', '', '기본형/슬림형', '', 1050000, '출장비+작업비 1,200,000원', 1030),
  ('labor|SPD|드럼커버 교체|기본형/슬림형', 'labor', 'SPD', '인건비', '드럼커버 교체', '', '기본형/슬림형', '', 150000, '출장비+작업비 300,000원', 1031),
  ('labor|SPD|드럼커버 교체|복구형', 'labor', 'SPD', '인건비', '드럼커버 교체', '', '복구형', '', 150000, '출장비+작업비 300,000원', 1032),
  ('labor|SPD|리모컨 설치|당사', 'labor', 'SPD', '인건비', '리모컨 설치', '', '당사', '', 150000, '출장비+작업비 300,000원', 1033),
  ('labor|SPD|리모컨 설치|타사자동문', 'labor', 'SPD', '인건비', '리모컨 설치', '', '타사자동문', '', 250000, '출장비+작업비 400,000원', 1034),
  ('labor|SPD|컨트롤러 교체|당사', 'labor', 'SPD', '인건비', '컨트롤러 교체', '', '당사', '', 150000, '출장비+작업비 300,000원', 1035),
  ('labor|SPD|컨트롤러 교체|타사자동문', 'labor', 'SPD', '인건비', '컨트롤러 교체', '', '타사자동문', '', 250000, '출장비+작업비 400,000원', 1036),
  ('labor|SPD|엔코더 교체|기본형/슬림형', 'labor', 'SPD', '인건비', '엔코더 교체', '', '기본형/슬림형', '', 150000, '출장비+작업비 300,000원', 1037),
  ('labor|SPD|엔코더 교체|복구형', 'labor', 'SPD', '인건비', '엔코더 교체', '', '복구형', '', 250000, '출장비+작업비 400,000원', 1038),
  ('labor|SPD|엔코더 교체|타사자동문', 'labor', 'SPD', '인건비', '엔코더 교체', '', '타사자동문', '', 350000, '출장비+작업비 500,000원', 1039),
  ('labor|SPD|보강대 교체|기본형/슬림형/복구형', 'labor', 'SPD', '인건비', '보강대 교체', '', '기본형/슬림형/복구형', '', 1050000, '출장비+작업비 1,200,000원', 1040),
  ('labor|SPD|출장 인쇄|단면', 'labor', 'SPD', '인건비', '출장 인쇄', '', '단면', '', 150000, '출장비+작업비 300,000원', 1041),
  ('labor|SPD|드럼 제조|', 'labor', 'SPD', '인건비', '드럼 제조', '', '', '', 300000, '출장비+작업비 600,000원', 1042),
  ('labor|OHD|판넬 교체|수납형/산업용', 'labor', 'OHD', '인건비', '판넬 교체', '', '수납형/산업용', '', 500000, '2인1조 기준 / 장비대 별도', 1043),
  ('labor|OHD|판넬 교체|주택차고문', 'labor', 'OHD', '인건비', '판넬 교체', '', '주택차고문', '', 300000, '', 1044),
  ('labor|OHD|판넬 교체|타사자동문', 'labor', 'OHD', '인건비', '판넬 교체', '', '타사자동문', '', 500000, '', 1045),
  ('labor|OHD|모터 교체|수납형/산업용', 'labor', 'OHD', '인건비', '모터 교체', '', '수납형/산업용', '', 500000, '', 1046),
  ('labor|OHD|모터 교체|주택차고문', 'labor', 'OHD', '인건비', '모터 교체', '', '주택차고문', '', 300000, '', 1047),
  ('labor|OHD|모터 교체|타사자동문', 'labor', 'OHD', '인건비', '모터 교체', '', '타사자동문', '', 400000, '', 1048),
  ('labor|OHD|와이어 교체|산업용', 'labor', 'OHD', '인건비', '와이어 교체', '', '산업용', '', 500000, '', 1049),
  ('labor|OHD|와이어 교체|주택차고문', 'labor', 'OHD', '인건비', '와이어 교체', '', '주택차고문', '', 300000, '', 1050),
  ('labor|OHD|스프링 교체|산업용', 'labor', 'OHD', '인건비', '스프링 교체', '', '산업용', '', 500000, '', 1051),
  ('labor|OHD|스프링 교체|주택차고문', 'labor', 'OHD', '인건비', '스프링 교체', '', '주택차고문', '', 300000, '', 1052),
  ('labor|OHD|체인 교체|수납형', 'labor', 'OHD', '인건비', '체인 교체', '', '수납형', '', 500000, '', 1053),
  ('labor|OHD|기본 출장비|수납형/산업용', 'labor', 'OHD', '인건비', '기본 출장비', '', '수납형/산업용', '', 300000, '', 1054),
  ('labor|OHD|기본 출장비|주택차고문', 'labor', 'OHD', '인건비', '기본 출장비', '', '주택차고문', '', 200000, '전체 점검 포함', 1055),
  ('labor|OHD|기본 출장비|타사자동문', 'labor', 'OHD', '인건비', '기본 출장비', '', '타사자동문', '', 400000, '', 1056),
  ('labor|OHD|철거비|', 'labor', 'OHD', '인건비', '철거비', '', '', '', 500000, '', 1057),
  ('labor|OHD|시공비|', 'labor', 'OHD', '인건비', '시공비', '', '', '', 700000, '장비대 별도 청구', 1058)
) AS v(source_key, kind, product_line, category, name, name_en, spec, unit, price, note, sort_order)
ON CONFLICT (source_key)
DO UPDATE SET
  kind = EXCLUDED.kind,
  product_line = EXCLUDED.product_line,
  category = EXCLUDED.category,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  spec = EXCLUDED.spec,
  unit = EXCLUDED.unit,
  price = EXCLUDED.price,
  note = EXCLUDED.note,
  sort_order = EXCLUDED.sort_order,
  updated_at = now()
WHERE public.support_as_unit_prices.deleted_at IS NULL;
