-- Update history metadata for Settings > 업데이트 내역
-- Safe to run on existing environments.

create table if not exists public.app_update_policy (
  id bigint generated by default as identity primary key,
  min_version text not null,
  latest_version text not null,
  store_url text,
  force_update boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.app_update_policy
  add column if not exists proposed_by text;

alter table public.app_update_policy
  add column if not exists release_notes jsonb;

alter table public.app_update_policy
  add column if not exists change_summary text;

-- Optional fallback aliases that app code can parse.
alter table public.app_update_policy
  add column if not exists proposer text;

alter table public.app_update_policy
  add column if not exists requested_by text;

alter table public.app_update_policy
  add column if not exists changes jsonb;

create index if not exists app_update_policy_updated_at_idx
  on public.app_update_policy (updated_at desc);

comment on column public.app_update_policy.proposed_by
  is '업데이트 제안자(예: 현장 운영팀, 영업팀)';

comment on column public.app_update_policy.release_notes
  is '권장: JSON 배열 문자열 목록, 예) ["항목1","항목2"]';
