-- A/S 단가표 부품 사진·도해 (2026.03.06 원본 PDF/엑셀)
ALTER TABLE public.support_as_unit_prices
  ADD COLUMN IF NOT EXISTS image_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS diagram_url text NOT NULL DEFAULT '';

COMMENT ON COLUMN public.support_as_unit_prices.image_url IS '부품 사진. assets/ 또는 https URL';
COMMENT ON COLUMN public.support_as_unit_prices.diagram_url IS '부품 도해. assets/ 또는 https URL';

UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_024.jpg', diagram_url = 'assets/as_unit_prices/part_024_d.jpg' WHERE source_key = 'part|SPD|C-1/C-2 기본형/슬림형|드럼 커버|DRUM COVER|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_026.jpg', diagram_url = 'assets/as_unit_prices/part_026_d.jpg' WHERE source_key = 'part|SPD|C-1/C-2 기본형/슬림형|가이드 레일|GUIDE RAIL(ㄱ)|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_027.jpg', diagram_url = 'assets/as_unit_prices/part_027_d.jpg' WHERE source_key = 'part|SPD|C-1/C-2 기본형/슬림형|프레임 커버|FRAME COVER|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_028.jpg', diagram_url = 'assets/as_unit_prices/part_028_d.jpg' WHERE source_key = 'part|SPD|C-1/C-2 기본형/슬림형|브러쉬 레일|BRUSH RAIL(ㄷ)|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_029.jpg', diagram_url = 'assets/as_unit_prices/part_029_d.jpg' WHERE source_key = 'part|SPD|C-1/C-2 기본형/슬림형|윈드바|WIND BAR|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_030.jpg', diagram_url = 'assets/as_unit_prices/part_030_d.jpg' WHERE source_key = 'part|SPD|C-1/C-2 기본형/슬림형|하단바|BOTTOM BAR|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_031.jpg', diagram_url = 'assets/as_unit_prices/part_031_d.jpg' WHERE source_key = 'part|SPD|C-3 복구형|드럼 커버|DRUM COVER|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_032.jpg', diagram_url = 'assets/as_unit_prices/part_032_d.jpg' WHERE source_key = 'part|SPD|C-3 복구형|드럼 상부 커버|DRUM TOP COVER|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_033.jpg', diagram_url = 'assets/as_unit_prices/part_033_d.jpg' WHERE source_key = 'part|SPD|C-3 복구형|드럼 하부 커버|DRUM JOINT COVER|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_034.jpg', diagram_url = 'assets/as_unit_prices/part_034_d.jpg' WHERE source_key = 'part|SPD|C-3 복구형|PVC 가이드 레일|PVC GUIDE RAIL|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_035.jpg', diagram_url = 'assets/as_unit_prices/part_035_d.jpg' WHERE source_key = 'part|SPD|C-3 복구형|프레임 커버|FRAME COVER|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_036.jpg', diagram_url = 'assets/as_unit_prices/part_036_d.jpg' WHERE source_key = 'part|SPD|C-3 복구형|프레임 백커버|FRAME BACK COVER(ㄱ)|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_037.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SHEET 시트|블랙 시트(하단바)|1T SHEET (BOTTOM BAR)|M' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_038.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SHEET 시트|오렌지/그레이/블루 시트|2T SHEET|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_039.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SHEET 시트|투명창|CLEAR SHEET|m²' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_042.jpg', diagram_url = '' WHERE source_key = 'part|SPD|MOTOR 모터|반마력|HYPONIC 0.4KW (0.5HP)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_043.jpg', diagram_url = '' WHERE source_key = 'part|SPD|MOTOR 모터|1마력|HYPONIC 0.75KW (1HP)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_044.jpg', diagram_url = '' WHERE source_key = 'part|SPD|MOTOR 모터|2마력|HYPONIC 1.5KW (2HP)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_045.jpg', diagram_url = '' WHERE source_key = 'part|SPD|MOTOR 모터|반마력|ALTAX 0.4KW (0.5HP)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_046.jpg', diagram_url = '' WHERE source_key = 'part|SPD|MOTOR 모터|1마력|ALTAX 0.75KW (1HP)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_050.jpg', diagram_url = '' WHERE source_key = 'part|SPD|CONTROLLER 전자제어장치|메인보드|CONTROLLER (MAIN)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_051.jpg', diagram_url = '' WHERE source_key = 'part|SPD|CONTROLLER 전자제어장치|디스플레이보드|CONTROLLER (DISPLAY)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_055.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|엔코더|ENCODER|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_056.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|포토 센서|PHOTO SENSOR|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_057.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|루프 센서|LOOP SENSOR|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_058.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|어플리스 센서|MICROWAVE MOTION SENSOR|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_061.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|적외선 센서|INFRARED SENSOR|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_062.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|압력 센서|PRESSURE SENSOR|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_065.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|1점 스위치|1 POINT SWITCH|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_067.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|풀 스위치|PULL SWITCH|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_068.jpg', diagram_url = '' WHERE source_key = 'part|SPD|SENSOR/SWITCH 센서/스위치|근접 스위치|PROXIMITY SWITCH|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_074.jpg', diagram_url = '' WHERE source_key = 'part|SPD|REMOTE CONTROL 리모컨|리츠엔 수신기|RITS-N RECEPTION|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_075.jpg', diagram_url = '' WHERE source_key = 'part|SPD|REMOTE CONTROL 리모컨|리츠엔 송신기|RITS-N REMOCON|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_076.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-1 DRUM PART 기본형 드럼파트|사이드 브라켓|SIDE BRACKET|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_077.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-1 DRUM PART 기본형 드럼파트|베어링|BEARING|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_078.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-1 DRUM PART 기본형 드럼파트|샤프트|SHAFT|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_079.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-1 DRUM PART 기본형 드럼파트|롤파이프|ROLL PIPE|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_080.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-1 DRUM PART 기본형 드럼파트|백판|BACK HOUSING|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_081.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-1 DRUM PART 기본형 드럼파트|모터 커버|MOTOR COVER(SUS)|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_082.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-2 DRUM PART 슬림형 드럼파트|사이드 브라켓|SIDE BRACKET|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_083.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-2 DRUM PART 슬림형 드럼파트|베어링|BEARING|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_084.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-2 DRUM PART 슬림형 드럼파트|샤프트|SHAFT|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_085.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-2 DRUM PART 슬림형 드럼파트|PVC 롤파이프|PVC ROLL PIPE|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_086.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-2 DRUM PART 슬림형 드럼파트|백판|BACK HOUSING|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_087.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-2 DRUM PART 슬림형 드럼파트|모터 하우징|MOTOR HOUSING|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_088.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-3 DRUM PART 복구형 드럼파트|사이드 브라켓|SIDE BRACKET|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_089.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-3 DRUM PART 복구형 드럼파트|베어링|BEARING|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_090.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-3 DRUM PART 복구형 드럼파트|샤프트|SHAFT|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_091.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-3 DRUM PART 복구형 드럼파트|롤파이프|ROLL PIPE|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_092.jpg', diagram_url = '' WHERE source_key = 'part|SPD|C-3 DRUM PART 복구형 드럼파트|기어|GEAR|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_093.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|CONTROLLER 전자제어장치|컨트롤러|CONTROLLER|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_094.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|CONTROLLER 전자제어장치|엔코더|ENCODER|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_095.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|MOTOR 모터|1마력|HYPONIC 0.75KW (1HP)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_096.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|MOTOR 모터|반마력|HYPONIC 0.4KW (0.5HP)|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_097.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|FRAME PART 프레임 파트|프레임 커버|FRAME COVER|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_098.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|FRAME PART 프레임 파트|가이드 레일(전면)|GUIDE RAIL (FRONT)|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_099.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|FRAME PART 프레임 파트|가이드 레일(후면)|GUIDE RAIL (REAR)|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_101.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|드럼|DRUM ASS''Y|SET' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_102.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|기어|GEAR|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_103.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|베어링|BEARING|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_104.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|베어링 하우징|BEARING HOUSING|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_105.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|샤프트|SHAFT|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_106.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|샤프트 서포터|SHAFT SUPPORT|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_107.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|체인 50번|CHAIN 50#|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_108.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|체인 60번|CHAIN 60#|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_109.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|DRUM PART 드럼 파트|롤파이프|ROLL PIPE|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_110.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|PANEL PART 판넬 파트|우레탄 판넬|URETHANE PANEL|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_111.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|PANEL PART 판넬 파트|판넬캡(상/하부)|PANEL CAP (TOP/BOTTOM)|m' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_112.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|PANEL PART 판넬 파트|엔드캡|END CAP|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_113.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|PANEL PART 판넬 파트|판넬 롤러|PANEL ROLLER|EA' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_114.jpg', diagram_url = '' WHERE source_key = 'part|OHD-수납형|PANEL PART 판넬 파트|채광창|WINDOW|' AND deleted_at IS NULL;
UPDATE public.support_as_unit_prices SET image_url = 'assets/as_unit_prices/part_118.jpg', diagram_url = '' WHERE source_key = 'part|OHD-산업용|PANEL PART 판넬 파트|우레탄 판넬|URETHANE PANEL|m' AND deleted_at IS NULL;
